# Generated by Django 5.0.3 on 2025-04-24 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hospital",
            name="phone",
        ),
        migrations.AddField(
            model_name="hospital",
            name="contact",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="hospitals/"),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="website",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
    ]
