# Generated by Django 5.0.3 on 2025-04-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketplaceitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("Food", "Food"),
                    ("Toys", "Toys"),
                    ("Bedding", "Bedding"),
                    ("Grooming", "Grooming"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="marketplaceitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="marketplaceitem",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
