# Generated by Django 5.0.3 on 2025-05-18 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitem',
            name='category',
            field=models.CharField(choices=[('toys', 'Toys'), ('food', 'Food'), ('accessories', 'Accessories'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_items_sold', to=settings.AUTH_USER_MODEL),
        ),
    ]
