# Generated by Django 5.0.3 on 2025-04-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_alter_marketplaceitem_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketplaceitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("food", "Pet Food"),
                    ("toys", "Toys"),
                    ("accessories", "Accessories"),
                    ("supplies", "Supplies"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
