# Generated by Django 5.0.3 on 2025-05-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_marketplaceitem_category_marketplaceitem_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplaceitem',
            options={'ordering': ['-created_at']},
        ),
    ]
