# Generated by Django 5.0.3 on 2025-05-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_marketplaceitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplaceitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Marketplace Item', 'verbose_name_plural': 'Marketplace Items'},
        ),
    ]
