# Generated by Django 5.0.3 on 2025-05-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_marketplaceitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplaceitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='marketplaceitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='marketplaceitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='marketplaceitem',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='marketplaceitem',
            name='updated_at',
        ),
    ]
