# Generated by Django 5.0.3 on 2025-05-05 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pet_health_status_alter_pet_vaccination_status'),
        ('marketplace', '0004_petlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlisting',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='core.pet'),
        ),
    ]
