# Generated by Django 5.0.3 on 2025-04-24 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_timestamps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="age",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="type",
            field=models.CharField(
                choices=[
                    ("dog", "Dog"),
                    ("cat", "Cat"),
                    ("bird", "Bird"),
                    ("fish", "Fish"),
                    ("reptile", "Reptile"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
