# Generated by Django 5.0.3 on 2025-04-25 04:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pet_age_alter_pet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/'),
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
