# Generated by Django 5.0.3 on 2025-04-25 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_marketplaceitem_created_at_marketplaceitem_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
