# Generated by Django 5.0.3 on 2025-04-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='health_status',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], default='good', max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vaccination_status',
            field=models.CharField(choices=[('fully_vaccinated', 'Fully Vaccinated'), ('partially_vaccinated', 'Partially Vaccinated'), ('not_vaccinated', 'Not Vaccinated'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
