# Generated by Django 5.0.3 on 2025-05-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pet_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='adoption_status',
            field=models.CharField(choices=[('available', 'Available for Adoption'), ('adopted', 'Adopted'), ('pending', 'Adoption Pending')], default='available', max_length=20),
        ),
    ]
