# Generated by Django 5.0.3 on 2025-05-17 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_marketplaceitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.listing'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='marketplace_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.marketplaceitem'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('listing__isnull', True), ('marketplace_item__isnull', False)), models.Q(('listing__isnull', False), ('marketplace_item__isnull', True)), _connector='OR'), name='cart_item_must_have_one_item'),
        ),
    ]
