# Generated by Django 5.0.3 on 2025-05-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='request_type',
            field=models.CharField(choices=[('adoption', 'Adoption'), ('exchange', 'Exchange')], default='adoption', max_length=20),
        ),
    ]
