# Generated by Django 5.0.3 on 2025-05-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_adoptionrequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='last_seen_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='lost_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('adoption', 'Adoption'), ('sale', 'Sale'), ('exchange', 'Exchange'), ('lost', 'Lost')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('adopted', 'Adopted'), ('removed', 'Removed'), ('found', 'Found')], default='available', max_length=20),
        ),
    ]
