# Generated by Django 5.0.3 on 2025-05-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_listing_last_seen_location_listing_lost_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostpet',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='last_seen_location',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='lost_date',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('adoption', 'Adoption'), ('sale', 'Sale'), ('exchange', 'Exchange')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('adopted', 'Adopted'), ('removed', 'Removed')], default='available', max_length=20),
        ),
        migrations.DeleteModel(
            name='FoundPet',
        ),
        migrations.DeleteModel(
            name='LostPet',
        ),
    ]
